name: cs5346-otot-a3-chuxin
channels:
  - defaults
dependencies:
  - bokeh=3.0.3
  - ipywidgets=7.6.5
  - matplotlib=3.6.2
  - matplotlib-inline=0.1.6
  - numpy=1.23.5
  - pandas=1.5.2
  - python=3.10.9
  - seaborn=0.12.2
